[package]
name = "e2e-test"
version = "0.0.2"
edition = "2018"
license-file = "../LICENSE"
publish = false

[dependencies]
radius = { version = "0.0.2", path = "../radius" }
tokio = { version = "0.3.5", features = ["signal", "net"] }
async-trait = "0.1.42"
